linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude unused parameter warnings in interface implementations
    - linters:
        - revive
      text: "unused-parameter"
    # Exclude exported comment warnings for LocationManager methods (documented inline in Backend interface)
    - linters:
        - revive
      text: "exported method Backend\\.(ListLocations|LocationExists|CreateLocation|ListItemsInLocation)"

run:
  timeout: 5m
  tests: true

severity:
  default-severity: error
  rules:
    - linters:
        - revive
      severity: warning
