codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 5%
        base: auto

    patch:
      default:
        target: 80%
        threshold: 10%

ignore:
  - "backends/**"  # Backend implementations require external CLI tools
  - "**/*_test.go"  # Test files
  - "**/example_test.go"  # Example files

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true
